# Generated by Django 4.1.3 on 2022-11-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parlourhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parlourhouse_address', models.CharField(default='', max_length=50)),
                ('parlourhouse_name', models.CharField(default='', max_length=50)),
                ('parlourhouse_city', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
