# Generated by Django 4.1.3 on 2022-11-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlourhouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parlourhouse',
            old_name='parlourhouse_city',
            new_name='parlour_city',
        ),
    ]
