# Generated by Django 4.1.3 on 2022-11-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jewelleryhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewelleryhouse_brand', models.CharField(max_length=50)),
                ('jewelleryhouse_name', models.CharField(max_length=50)),
                ('jewelleryhouse_quailty', models.CharField(max_length=64)),
                ('jewelleryhouse_images', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
