# Generated by Django 4.1.3 on 2022-11-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fashionhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fashion_name', models.CharField(max_length=50)),
                ('fashionhouse_address', models.CharField(max_length=50)),
                ('about_fashionhouse', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
